version: 2.1
orbs:
  aws-cli: circleci/aws-cli@5.2.0
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:23.0.2
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Verify working directory
          command: pwd && ls -la  
      - run:
          name: Build the project
          command: mvn clean package
      - run:
          name: Run tests
          command: mvn test
      - persist_to_workspace:
          root: .
          paths:
            - target/app.jar

  sonar_scan:
    docker:
      - image: cimg/openjdk:23.0.2
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: SonarCloud Scan
          command: mvn sonar:sonar -Dsonar.organization=Nglicloud -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN

  deploy:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install AWS CLI
          command: sudo apt-get install -y awscli
      - run:
          name: Upload to S3
          command: aws s3 cp target/app.jar s3://dattas-bucket/app.jar

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - sonar_scan:
          requires:
            - build
      - deploy:
          requires:
            - sonar_scan